### ISSUE TITLE
各位大佬，提取pdf中的图形出现如下错误，该怎么解决呢？

### ISSUE THREAD

**Issue by denghb001** [CrystalEye42/OpenChemIE#14]
运行脚本如下：
import torch
from openchemie import OpenChemIE
model = OpenChemIE(device=torch.device('cpu'))
figure_results = model.extract_molecules_from_figures_in_pdf(pdf_path)

# 错误信息
Traceback (most recent call last):
  File "D:\anaconda3\envs\openchemie\lib\site-packages\IPython\core\interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-a1d8d2af7d88>", line 1, in <module>
    figure_results = model.extract_molecules_from_figures_in_pdf(pdf_path)
  File "D:\anaconda3\envs\openchemie\lib\site-packages\openchemie\interface.py", line 272, in extract_molecules_from_figures_in_pdf
    figures = self.extract_figures_from_pdf(pdf, num_pages=num_pages, output_bbox=True)
  File "D:\anaconda3\envs\openchemie\lib\site-packages\openchemie\interface.py", line 203, in extract_figures_from_pdf
    return table_ext.extract_all_tables_and_figures(pages, self.pdfparser, content='figures')
  File "D:\anaconda3\envs\openchemie\lib\site-packages\openchemie\interface.py", line 74, in pdfparser
    self.init_pdfparser()
  File "D:\anaconda3\envs\openchemie\lib\site-packages\openchemie\interface.py", line 85, in init_pdfparser
    self._pdfparser = lp.AutoLayoutModel(config_path, model_path=ckpt_path, device=self.device.type)
  File "D:\anaconda3\envs\openchemie\lib\site-packages\layoutparser\models\auto_layoutmodel.py", line 64, in AutoLayoutModel
    return ALL_AVAILABLE_BACKENDS[backend_name](
  File "D:\anaconda3\envs\openchemie\lib\site-packages\layoutparser\models\effdet\layoutmodel.py", line 138, in __init__
    self._initialize_model(config_path, model_path, label_map, extra_config)
  File "D:\anaconda3\envs\openchemie\lib\site-packages\layoutparser\models\effdet\layoutmodel.py", line 164, in _initialize_model
    model_path = PathManager.get_local_path(model_path)
  File "D:\anaconda3\envs\openchemie\lib\site-packages\iopath\common\file_io.py", line 1251, in get_local_path
    bret = handler._get_local_path(path, force=force, **kwargs)
  File "D:\anaconda3\envs\openchemie\lib\site-packages\layoutparser\models\effdet\catalog.py", line 64, in _get_local_path
    return PathManager.get_local_path(model_url, **kwargs)
  File "D:\anaconda3\envs\openchemie\lib\site-packages\iopath\common\file_io.py", line 1251, in get_local_path
    bret = handler._get_local_path(path, force=force, **kwargs)
  File "D:\anaconda3\envs\openchemie\lib\site-packages\iopath\common\file_io.py", line 835, in _get_local_path
    with file_lock(cached):
  File "D:\anaconda3\envs\openchemie\lib\site-packages\portalocker\utils.py", line 302, in __enter__
    return self.acquire()
  File "D:\anaconda3\envs\openchemie\lib\site-packages\portalocker\utils.py", line 256, in acquire
    fh = self._get_fh()
  File "D:\anaconda3\envs\openchemie\lib\site-packages\portalocker\utils.py", line 313, in _get_fh
    return open(  # noqa: SIM115
OSError: [Errno 22] Invalid argument: 'C:\\Users\\86182/.torch/iopath_cache\\s/gxy11xkkiwnpgog\\publaynet-tf_efficientdet_d1.pth.tar?dl=1.lock'

**Comment by Plp15079287565** [comment]
我的也是这个问题,你是解决了没有, 报这个错OSError: [Errno 22] Invalid argument: 'C:\\Users\\Administrator/.torch/iopath_cache\\s/gxy11xkkiwnpgog\\publaynet-tf_efficientdet_d1.pth.tar?dl=1.lock'
